<?php
/**
 * ScheduleEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Schedule API
 *
 * ConnectWise Schedule API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Schedule;

/**
 * ScheduleEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description ScheduleEntry
/**
 * @package     Spinen\ConnectWise\Clients\Schedule
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ScheduleEntry"
     */
    public function testScheduleEntry()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "where"
     */
    public function testPropertyWhere()
    {

    }

    /**
     * Test attribute "date_start"
     */
    public function testPropertyDateStart()
    {

    }

    /**
     * Test attribute "date_end"
     */
    public function testPropertyDateEnd()
    {

    }

    /**
     * Test attribute "reminder"
     */
    public function testPropertyReminder()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "span"
     */
    public function testPropertySpan()
    {

    }

    /**
     * Test attribute "done_flag"
     */
    public function testPropertyDoneFlag()
    {

    }

    /**
     * Test attribute "acknowledged_flag"
     */
    public function testPropertyAcknowledgedFlag()
    {

    }

    /**
     * Test attribute "owner_flag"
     */
    public function testPropertyOwnerFlag()
    {

    }

    /**
     * Test attribute "allow_schedule_conflicts_flag"
     */
    public function testPropertyAllowScheduleConflictsFlag()
    {

    }

    /**
     * Test attribute "add_member_to_project_flag"
     */
    public function testPropertyAddMemberToProjectFlag()
    {

    }

    /**
     * Test attribute "project_role_id"
     */
    public function testPropertyProjectRoleId()
    {

    }

    /**
     * Test attribute "mobile_guid"
     */
    public function testPropertyMobileGuid()
    {

    }

    /**
     * Test attribute "close_date"
     */
    public function testPropertyCloseDate()
    {

    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
