<?php
/**
 * ScheduleEntriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Schedule API
 *
 * ConnectWise Schedule API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Schedule;

use \Spinen\ConnectWise\Clients\Schedule\Configuration;
use \Spinen\ConnectWise\Clients\Schedule\ApiClient;
use \Spinen\ConnectWise\Clients\Schedule\ApiException;
use \Spinen\ConnectWise\Clients\Schedule\ObjectSerializer;

/**
 * ScheduleEntriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleEntriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for scheduleEntriesCountGet
     *
     * .
     *
     */
    public function testScheduleEntriesCountGet()
    {

    }

    /**
     * Test case for scheduleEntriesGet
     *
     * .
     *
     */
    public function testScheduleEntriesGet()
    {

    }

    /**
     * Test case for scheduleEntriesIdDelete
     *
     * .
     *
     */
    public function testScheduleEntriesIdDelete()
    {

    }

    /**
     * Test case for scheduleEntriesIdGet
     *
     * .
     *
     */
    public function testScheduleEntriesIdGet()
    {

    }

    /**
     * Test case for scheduleEntriesIdPatch
     *
     * .
     *
     */
    public function testScheduleEntriesIdPatch()
    {

    }

    /**
     * Test case for scheduleEntriesIdPut
     *
     * .
     *
     */
    public function testScheduleEntriesIdPut()
    {

    }

    /**
     * Test case for scheduleEntriesPost
     *
     * .
     *
     */
    public function testScheduleEntriesPost()
    {

    }

}
