<?php
/**
 * ScheduleTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Schedule API
 *
 * ConnectWise Schedule API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Schedule;

use \Spinen\ConnectWise\Clients\Schedule\Configuration;
use \Spinen\ConnectWise\Clients\Schedule\ApiClient;
use \Spinen\ConnectWise\Clients\Schedule\ApiException;
use \Spinen\ConnectWise\Clients\Schedule\ObjectSerializer;

/**
 * ScheduleTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for scheduleTypesCountGet
     *
     * .
     *
     */
    public function testScheduleTypesCountGet()
    {

    }

    /**
     * Test case for scheduleTypesGet
     *
     * .
     *
     */
    public function testScheduleTypesGet()
    {

    }

    /**
     * Test case for scheduleTypesIdDelete
     *
     * .
     *
     */
    public function testScheduleTypesIdDelete()
    {

    }

    /**
     * Test case for scheduleTypesIdGet
     *
     * .
     *
     */
    public function testScheduleTypesIdGet()
    {

    }

    /**
     * Test case for scheduleTypesIdPatch
     *
     * .
     *
     */
    public function testScheduleTypesIdPatch()
    {

    }

    /**
     * Test case for scheduleTypesIdPut
     *
     * .
     *
     */
    public function testScheduleTypesIdPut()
    {

    }

    /**
     * Test case for scheduleTypesPost
     *
     * .
     *
     */
    public function testScheduleTypesPost()
    {

    }

}
