<?php
/**
 * ScheduleStatusesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Schedule API
 *
 * ConnectWise Schedule API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Schedule;

use \Spinen\ConnectWise\Clients\Schedule\Configuration;
use \Spinen\ConnectWise\Clients\Schedule\ApiClient;
use \Spinen\ConnectWise\Clients\Schedule\ApiException;
use \Spinen\ConnectWise\Clients\Schedule\ObjectSerializer;

/**
 * ScheduleStatusesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Schedule
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleStatusesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for scheduleStatusesCountGet
     *
     * .
     *
     */
    public function testScheduleStatusesCountGet()
    {

    }

    /**
     * Test case for scheduleStatusesGet
     *
     * .
     *
     */
    public function testScheduleStatusesGet()
    {

    }

    /**
     * Test case for scheduleStatusesIdDelete
     *
     * .
     *
     */
    public function testScheduleStatusesIdDelete()
    {

    }

    /**
     * Test case for scheduleStatusesIdGet
     *
     * .
     *
     */
    public function testScheduleStatusesIdGet()
    {

    }

    /**
     * Test case for scheduleStatusesIdPatch
     *
     * .
     *
     */
    public function testScheduleStatusesIdPatch()
    {

    }

    /**
     * Test case for scheduleStatusesIdPut
     *
     * .
     *
     */
    public function testScheduleStatusesIdPut()
    {

    }

    /**
     * Test case for scheduleStatusesPost
     *
     * .
     *
     */
    public function testScheduleStatusesPost()
    {

    }

}
